name: Build and Push Docker Image

# Dit start de build zodra je iets naar de 'main' branch pusht
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Dit is de cloud VM die het werk doet

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: goudvisvis/csharp-kernel:0.0.1